### ISSUE TITLE
Offsets for 2022 06 29

### ISSUE THREAD

**Issue by AllenSeitz** [olji/Reflux#10]
I wanted to be polite and not nag you about this. But it's been two weeks and I thought you might like to know that someone else cares!

How are you finding these offsets? Is this something that I can do for you with a pull request? I've written a memory scraper for an older version of Infinitas so I'm familiar with the concepts. I've found my own offsets before too but I don't know how you do yours.

For example to find the song database do you just open the heap in Cheat Engine and "ctrl-f" for "5.1.1."? Which offset do you then save? If you have a routine for finding the others I'd be glad to do it for you. Thank you for publishing and maintaining Reflux.

**Comment by olji** [comment]
I've been fiddling about with other stuff and haven't played much infinitas lately, but I've updated the offsets to 20220629 now.

I also included a document that streamlines the offset searching quite a bit which has helped people to update the offsets by themselves, I thought I had already pushed it here but apparently that wasn't the case.

**Comment by AllenSeitz** [comment]
Thank you!
