### ISSUE TITLE
Problem With New Offsets

### ISSUE THREAD

**Issue by AllenSeitz** [olji/Reflux#11]
I tried to find my own offsets. I'm pretty sure I did it correctly:

P2D:J:B:A:2023042600
songList = 0x14246A510
playData = 0x141A4E3FC
judgeData = 0x141CFA7FC
playSettings = 0x141A4E160
unlockdata = 0x141D02800
currentsong = 0x141CFA970
datamap = 0x14284F658

However the program hangs at "Hooked to process, waiting for songlist to be loaded..." even though I'm on the songwheel.

I'm running 1.12 and this week's patch of Infinitas.

**Comment by olji** [comment]
When it's waiting for songlist to be loaded it's checking two things:
1. The first entry in the address of songList is "5.1.1.", to make sure the song list is loaded
2. The first entry in the address of unlockdata is 1000, to make sure the array of unlock information is loaded, as there's a short time after the song list is populated where it's still empty.

Your unlock data seem to be pointing at 20016 in the middle of that array, so as it doesn't match with 1000 it takes that as the array of unlock information not being loaded yet. 
The offset finding document brings it up briefly at the last paragraph of that section so it's somewhat easy to miss. I just use 20016 as an example ID that's unique enough to give a single result in static memory, but one can tailor a more advanced query to find the start point automatically as well.

If you change unlock data to 0x141CFD980 everything else should work I think. Did a quick test with your offsets and everything else seemed to work fine.

**Comment by AllenSeitz** [comment]
Thank you for in the depth explanation! I see my mistake now. Aren't you going to push these offsets to prod, too?

**Comment by olji** [comment]
Was quite tired and forgot about it at the time. Okapi pushed new offsets in the meantime and from a quick comparison it seems you were 24 bytes off with the playdata offset as well, which would likely be the line below in CE memory view. I must've overlooked the chart name/difficulty and lamp when I was looking at the play results printout, or it got handled from the fallback on exception when reading from that address.

Anyway, everything seems to be resolved now so I'll be closing this.
